[book]
title = "Quantum Computing: a candid introduction"
authors = []
language = "en"
src = "src"

[output.html]
mathjax-support = true
additional-js = ["mathjax-fallback.js", "comments.js"]
site-url = "/qcfieldscourse/"
git-repository-url = "https://github.com/elhyc/qcfieldscourse"
edit-url-template = "https://github.com/elhyc/qcfieldscourse/edit/main/{path}"
git-repository-icon = "fab-github"
