[book]
title = "Quantum Computing: a Crash Course"
authors = []
language = "en"
src = "src"

[output.html]
mathjax-support = true
site-url = "/qcfieldscourse/"
git-repository-url = "https://github.com/elhyc/qcfieldscourse"
edit-url-template = "https://github.com/elhyc/qcfieldscourse/edit/main/{path}"
git-repository-icon = "fab-github"
